server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $tuma_api http://tuma-api:8080;
        proxy_pass $tuma_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /e/ {
        set $tuma_api http://tuma-api:8080;
        proxy_pass $tuma_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /sink/ {
        set $tuma_api http://tuma-api:8080;
        proxy_pass $tuma_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
